import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Form from "@/components/Form";
import Todo from "@/components/Todo";
import { useState, useEffect } from "react";
import { db } from "../firebase";
import {
  query,
  collection,
  onSnapshot,
  updateDoc,
  doc,
} from "firebase/firestore";
import { async } from "@firebase/util";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todos, setTodos] = useState([]);

  //Create todo

  const createTodo = async (e) => {
    e.preventDefault(e);
  };
  //Read todo from firebase

  useEffect(() => {
    const q = query(collection(db, "todos"));
    const unsubscribe = onSnapshot(q, (querySnapshot) => {
      let todoArr = [];
      querySnapshot.forEach((doc) => {
        todoArr.push({ ...doc.data(), id: doc.id });
      });
      setTodos(todoArr);
    });
    return () => unsubscribe();
  }, []);

  //Update todo in firebase

  const toggleComplete = async (todo) => {
    await updateDoc(doc(db, "todos", "todo.id"), {
      completed: !todo.completed,
    });
  };
  //Delete todo

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="container">
          <h3 className="heading">Todo App</h3>
          <Form createTodo={createTodo} />

          <ul>
            {todos.map((todo, index) => (
              <Todo key={index} todo={todo} toggleComplete={toggleComplete} />
            ))}
          </ul>

          <p className="todo-count">You have 3 todo now</p>
        </div>
      </main>
    </>
  );
}
